// pages/index.js
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <h1>ホーム</h1>
        <Link href="/posts/FirstPost">
          <a>Go to Blog</a>
        </Link>
      </nav>
    </div>
  );
}
